variables:
      GIT_SUBMODULE_STRATEGY: recursive
      PUSH_IMAGE: "nanolabs-notebook"
image: ${IMAGE}

stages:
    - build
    - push
build:docker:
    stage: build
    before_script:
        - apk add make bash openssl
    script:
        - make base-notebook
        - make picolabs-notebook
        - make nanolabs-notebook

.push-internal: &push-internal
    stage: push
    before_script:
        - REG=git.oxfordnanolabs.local:4567
        - echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${REG}

## Pushing commits on branches
push-commit-internal:
    <<: *push-internal
    script:
        - TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
        - docker tag ontresearch/${PUSH_IMAGE}:latest ${TAG}
        - docker push ${TAG}
    except:
        - tags

## Pushing a tag internally
push:tag-internal:
    <<: *push-internal
    script:
        - TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_TAG}
        - docker tag ontresearch/${PUSH_IMAGE}:latest ${TAG}
        - docker push ${TAG}
    only:
        - tags

# Push tags to dockerhub
push-dockerhub:
    stage: push
    script:
        - TAG=ontresearch/${PUSH_IMAGE}:${CI_COMMIT_TAG}
        - echo ${DOCKERHUB_TOKEN} | docker login --username epi2melabs --password-stdin
        - docker tag ontresearch/${PUSH_IMAGE}:latest ${TAG}
        - docker push ${TAG}
    only:
        - tags
