variables:
      GIT_SUBMODULE_STRATEGY: recursive
      PUSH_IMAGE: "nanolabs-notebook"
image: ${IMAGE}

stages:
    - build
    - pushtags
    
build:docker:
    stage: build
    before_script:
        - apk add make bash openssl
        - REG=${ONTREGISTRY}
    script:
        - make base-notebook
        - make picolabs-notebook
        - make nanolabs-notebook
        - TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
        - if [[ ${CI_COMMIT_BRANCH} == 'dev' ]]; then 
              echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${REG};
              docker tag ontresearch/${PUSH_IMAGE}:latest ${TAG};
              docker push ${TAG};
          fi
    only:
        - branches

.pushstub: &pull_tag
    stage: pushtags
    before_script:
        - REG=${ONTREGISTRY}
        - ORIG_TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
        - docker pull ${ORIG_TAG}
    only:
        - tags

# Push tag to ONT
push:tag-internal:
    <<: *pull_tag
    script:
        - echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${REG}
        - TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_TAG}
        - docker tag ${ORIG_TAG} ${TAG}
        - docker push ${TAG}

# Push tag to dockerhub
push:tag-dockerhub:
    <<: *pull_tag
    script:
        - echo ${DOCKERHUB_TOKEN} | docker login --username epi2melabs --password-stdin
        - TAG=ontresearch/${PUSH_IMAGE}:${CI_COMMIT_TAG}
        - docker tag ${ORIG_TAG} ${TAG}
        - docker push ${TAG}
