variables:
      GIT_SUBMODULE_STRATEGY: recursive
      PUSH_IMAGE: "nanolabs-notebook"
      GUPPY: ont-guppy-cpu_3.5.2_linux64.tar.gz
image: ${IMAGE}

stages:
    - fetch
    - build
    - push

fetch:guppy:
    stage: fetch
    script:
        # download guppy tar, remove basecalling models and programs
        - wget --no-check-certificate ${GUPPYREPO}/${GUPPY}
        - tar -xzvf ${GUPPY} && rm ${GUPPY}
        - rm ont-guppy-cpu/data/*.jsn ont-guppy-cpu/bin/guppy_basecall*
        - tar -czvf ${GUPPY} ont-guppy-cpu && rm -rf ont-guppy-cpu
    only:
        - branches
    artifacts:
        paths:
            - ${GUPPY}
    
build:docker:
    stage: build
    before_script:
        - apk add make bash git openssl
        - REG=${ONTREGISTRY}
    script:
        - tar -xzf ${GUPPY}
        - make base-notebook
        - make picolabs-notebook
        - make nanolabs-notebook
        - if [[ ${CI_COMMIT_BRANCH} == 'dev' ]]; then
              echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${REG};
              TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA};
              echo "Pushing ${TAG}";
              docker tag ontresearch/${PUSH_IMAGE}:latest ${TAG};
              docker push ${TAG};
          fi;
    only:
        - branches

.pushstub: &pull_tag
    stage: push
    before_script:
        - REG=${ONTREGISTRY}
        - ORIG_TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:dev-${CI_COMMIT_SHORT_SHA}
        - echo "Pulling ${ORIG_TAG}"
        - docker pull ${ORIG_TAG}

# Push tag to ONT
push:tag-internal:
    <<: *pull_tag
    script:
        - echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${REG}
        - TAG=${REG}/${CI_PROJECT_PATH}/${PUSH_IMAGE}:${CI_COMMIT_TAG}
        - echo "Pushing ${TAG}"
        - docker tag ${ORIG_TAG} ${TAG}
        - docker push ${TAG}
    only:
        - tags

# Push to dockerhub
.pushhubstub: &push_hub
    <<: *pull_tag
    script:
        - echo ${DOCKERHUB_TOKEN} | docker login --username epi2melabs --password-stdin
        - echo "Pushing ${TAG}"
        - docker tag ${ORIG_TAG} ${TAG}
        - docker push ${TAG}

# Push tag to dockerhub
push:tag-dockerhub:
    <<: *push_hub
    variables:
        TAG: ontresearch/${PUSH_IMAGE}:${CI_COMMIT_TAG}
    only:
        - tags

# Push dev commit to dockerhub
push:dev-dockerhub:
    <<: *push_hub
    variables:
        TAG: ontresearch/${PUSH_IMAGE}:dev
    only:
        - /^dev$/
    except:
        - tags
